### ISSUE TITLE
AviSynth Support

### ISSUE THREAD

**Issue by Anime4000** [Anime4000/IFME#20]
Now I adding AviSynth support but for Windows only. As [@OneVoltTen](https://github.com/OneVoltTen) request. IFME 4.9.5+

**To Use AviSynth:**
1. You need install [AviSynth 2.6 ST](http://avisynth.nl/index.php/Main_Page)
2. You need install [K-Lite Codec Pack Mega](http://codecguide.com/download_k-lite_codec_pack_mega.htm) *Select Option 9: Lot of Stuff*
3. Script that use MT (Multi Thread) version, [please use this](http://forum.doom9.org/showthread.php?t=148782)

**Supported:**
1. Currently available in Windows only
2. IFME only accept *.avs script that use `DirectShowSource`

**Todo List**
- [x] Integrate AviSynth and prevent accepting *.avs file if AviSynth not installed
- [x] Read and Convert *.avs file
- [x] Script Editor
- [x] Easily generate *convert to 60fps* script

**Comment by SailorOnDaTea** [comment]
"2. IFME only accept *.avs script that use |DirectShowSource"

Does this mean, with avisynth, we can trick ifme to use DirectShow for 
input, even without effects?

_Because normally __works something like this__:_
file>ffmpeg>|x265>muxer>file

_but with avisynth now we can add directshow filters like this_
file>*directshow*>avisynth>ffmpeg>x265>muxer>file

So it means we can actually use any directshow filter we want
Right?

**Comment by OneVoltTen** [comment]
You're awesome thanks for adding AviSynth support so fast. I'll let you know what I think after I've done a few encodes.

**Comment by Anime4000** [comment]
@SailorOnDaTea YES!... you can trick IFME :trollface: not to use FFmpeg bundled, by using AviSynth you can do scripting and choose any decoder as you like :+1: even without effect!

@OneVoltTen I add AviSynth because I learn it, it's come with ultimate effect and and functionality also I impressed with `svpflow` plugins where making **23.976** become **60fps** :top:

**Comment by Anime4000** [comment]
Help you create 60fps video
![ifme v4 9 5 0 twin angel](https://cloud.githubusercontent.com/assets/1908715/7009288/ce079f92-dccb-11e4-93d3-093e226b6668.png)
Edit AviSynth script :+1: 
![ifme v4 9 5 0 twin angel 1](https://cloud.githubusercontent.com/assets/1908715/7009291/d21e006c-dccb-11e4-89c9-b47c165eac56.png)

**Comment by OneVoltTen** [comment]
GPU acceleration, is that only usable with specific AviSynth filters and will it effect video quality?

**Comment by Anime4000** [comment]
spirton.com said it may degrade video quality if use GPU,
I embedding SVPFlow AviSynth plugins and avsi script so that comes with GPU support.

**Comment by L33tSheep** [comment]
Hello ! Maybe I did something wrong but i got this : 

![2f4d56b75c](https://cloud.githubusercontent.com/assets/1764453/8111689/899bdbcc-1063-11e5-815b-873d2a5713b5.png)

**Comment by Anime4000** [comment]
Hello! Try any of these release:
https://github.com/Anime4000/IFME/releases

make sure codec is properly installed, AviSynth using decoder that installed on your computer, also check the avs script is working, you can test play via MPC-HC 32bit

**Comment by L33tSheep** [comment]
Hello, wile using your latest release it seems that there's no trace of avisynth in the /addons/ folder. Is the user has to add it manually ?

**Comment by Anime4000** [comment]
ah... I forgot to add avs2pipe.exe
please copy to newer one :+1:

**Comment by L33tSheep** [comment]
Did it and... It worked perfectly ! Thanks for the help and all the amazing work you're doing. May IFMEGO be here soon ;)

**Comment by Anime4000** [comment]
IFME Go (v5.x) support AviSynth natively :+1:
